### ISSUE TITLE
Great Initiative -> Needs Readme.md

### ISSUE THREAD

**Issue by asishadhikari** [prajjwaldangal/ourOS#1]
This could be where we can practice good collaborating standards! **How about a nice Readme? ;)** [Here](https://opensource.guide/how-to-contribute/#how-to-submit-a-contribution) is a good resource about setting up good standards for collaboration (consider turning it open source too e.g contributions guidelines etc... ) @prajjwaldangal

**Comment by prajjwaldangal** [comment]
Thanks for the thoughful comments. I have updated the readme.
Given that the repo was open-sourced from from early on, I have managed to rename it to ourOS for inclusion sake. Cheers!
